name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.16", "1.15", "1.14", "1.13"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: Run build
        run: go build ./...
      - name: Run testing
        run: go test -v ./...
